name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Run tests
        run: go test -v ./...

      - name: Build Linux binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o secret-agent ./cmd/agent/main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: secret-agent
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}